#!/usr/bin/env php
<?php

$container = require(__DIR__ . '/../bootstrap.php');
/** @var \KutnyLib\Application\IApplication $daemon */
$daemon = $container->get('mail.queue.mail_queue_daemon');
$daemon->engage();
